name: http_xtra
description: Http encapsulation to parse easily
version: 0.0.2
repository: https://github.com/AlexandreCollin/HttpXtra

environment:
  sdk: ^3.5.3

dependencies:
  http: ^1.2.2

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
